# Default values for bitholla-hollaex-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imageRegistry: bitholla/hollaex-web
dockerTag:
  
imagePullSecrets:
  - name: docker-registry-secret

stable:
  replicaCount: 1

nodeSelector: {}

autoScaling:
  hpa:
    enable: false 
    maxReplicas: 4
    avgMemory: 500000000

podRestart_webhook_url:
  
resources:
  limits:

    memory: "100Mi"
  requests:
    cpu: "10m"
    memory: "100Mi"   
  

