{{- if .Values.pvc.create }}

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{.Values.pvc.name}}
  namespace: {{.Release.namespace}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{.Values.pvc.size}}

{{- end }}
