apiVersion: v1
kind: Service
metadata:
  name: {{.Release.Name}}
  namespace: {{.Release.namespace}}
  labels:
    app: {{.Release.Name}}
spec:
  {{if .Values.NodePort.enable }}

  type: NodePort
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: {{.Values.nodePort}}

  {{ else }}

  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432

  {{ end }}
      
  selector:
    app: {{.Release.Name}}
